title: Resilient Analytics
description: Empowering resilience through advanced analytics and data-driven insights.
theme: just-the-docs

url: ResilienceAnalytics.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
