title: Resilient Analytics
description: Empowering resilience through advanced analytics and data-driven insights.
theme: just-the-docs

url: ResilienceAnalytics.github.io

aux_links:
  Twitter: https://twitter.com/halxor149
  
footer_scripts:
  - "https://polyfill.io/v3/polyfill.min.js?features=es6"
  - "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
