title: Resilient Analytics
description: Empowering resilience through advanced analytics and data-driven insights.
theme: just-the-docs

url: ResilienceAnalytics.github.io

aux_links:
  Twitter: https://twitter.com/halxor149
  
nav_external_links_new_tab: true

<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-KRHFQLKX');</script>
<!-- End Google Tag Manager -->
