title: Resilient Analytics
description: Empowering resilience through advanced analytics and data-driven insights.
theme: just-the-docs

url: ResilienceAnalytics.github.io

aux_links:
  Twitter: https://twitter.com/halxor149
